// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD39r2EmwuIJotLrZGi0jNMqlKxgux8EvE',
    appId: '1:941309510734:web:fd0bfd58e77b45ca8a6f1f',
    messagingSenderId: '941309510734',
    projectId: 'inventory-manage-app',
    authDomain: 'inventory-manage-app.firebaseapp.com',
    storageBucket: 'inventory-manage-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5v_sxfA9e4wYKCYYPIw-c0rAT5FE1VY',
    appId: '1:941309510734:android:9b2247dc845733dd8a6f1f',
    messagingSenderId: '941309510734',
    projectId: 'inventory-manage-app',
    storageBucket: 'inventory-manage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuIwKncyHqshdqP0uD3WZbBEQV41_NCY',
    appId: '1:941309510734:ios:e6c9539d9c2774cf8a6f1f',
    messagingSenderId: '941309510734',
    projectId: 'inventory-manage-app',
    storageBucket: 'inventory-manage-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeuIwKncyHqshdqP0uD3WZbBEQV41_NCY',
    appId: '1:941309510734:ios:e6c9539d9c2774cf8a6f1f',
    messagingSenderId: '941309510734',
    projectId: 'inventory-manage-app',
    storageBucket: 'inventory-manage-app.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD39r2EmwuIJotLrZGi0jNMqlKxgux8EvE',
    appId: '1:941309510734:web:2c6292943be8f5e48a6f1f',
    messagingSenderId: '941309510734',
    projectId: 'inventory-manage-app',
    authDomain: 'inventory-manage-app.firebaseapp.com',
    storageBucket: 'inventory-manage-app.firebasestorage.app',
  );
}
